# 应用端口号
server.port: 8150

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.156.86:4657/sp2p_hzcf?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
    username: query
    password: Dikdk251df5sdEFD2DFDe #
# 日志文件配置
logging:
  logHome: D:/logs/safekeep-report # 日志路径
  envNameCN: 开发环境 # 环境中文名
  emailTo: guichang@hzed.com # 邮件接收者，多个用逗号隔开

#======================================= 系统参数 开始 =======================================#

#======================================= 系统参数 结束 =======================================#


