# 应用端口号
server.port: 8150

# TODO 密码加密 https://blog.csdn.net/linhongwangok/article/details/79076178;https://github.com/ulisesbocchio/jasypt-spring-boot
spring:
  profiles.active: dev # 环境
  application.name: easy-get
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.30.91:3306/easy-get?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
    username: root
    password: 123456
  # Resid相关配置
  redis:
    database: 0
    host: 10.10.30.37
    port: 3037
    password: masterpass

# 日志文件配置
logging:
  config: classpath:config/logback-spring.xml # 配置文件路径
  logHome: D:/logs/easy-get # 日志路径
  appNameCN: 印尼借贷项目 # 应用中文名
  envNameCN: 开发环境 # 环境中文名
  emailTo: guichang@hzed.com # 邮件接收者，多个用逗号隔开

#======================================= 系统参数 开始 =======================================#

#======================================= 系统参数 结束 =======================================#