# 应用端口号
server.port: 8150
# 默认根路径
server.context-path: /hzed/easy-get
# 加密
jasypt.encryptor.password: sdfhfw09GDS20403

spring:
  resources.static-locations: file:${system.imgUploadPath},classpath:/META-INF/resources/,classpath:/swagger/ # 静态资源文件路径，多个用逗号隔开 ,classpath:/public/,file:${web.upload-path}
  profiles.active: dev # 环境
  application.name: easy-get
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.30.36:3306/easy_get?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
    username: ENC(wD8fKKuFx4GcCaFsCnj3eg==) # 用户密文 明文用户：root
    password: ENC(c2BWF7K9ElGY0GZbWDmpfAaUhTuqYvie) # 密码密文 明文密码：rootroot
  # Resid相关配置
  redis:
    database: 0
    host: 10.10.30.37
    port: 3037
    password: masterpass
  # 国际化配置
  messages:
    basename: i18n/messages
    encoding: utf-8
    cacheSeconds: 86400 # 24小时
  # rabbitmq配置
  rabbitmq:
    host: 10.10.30.114
    port: 5672
    username: user
    password: password
    publisher-confirms: true
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual

# 日志文件配置
logging:
  config: classpath:config/logback-spring.xml # 配置文件路径
  logHome: D:/logs/easy-get # 日志路径
  saLogPath: ${logging.logHome}/sa/sa.log    # 神策测试环境和生产环境LogAgent日志目录
  appNameCN: 印尼借贷项目 # 应用中文名
  envNameCN: 开发环境 # 环境中文名
  emailTo: guichang@hzed.com # 邮件接收者，多个用逗号隔开

# 阿里云配置 暂废弃
#aliyun:
#  endpoint: http://oss-cn-shenzhen.aliyuncs.com
#  accessKeyId: LTAIxzelwCX3fyTQ
#  accessKeySecret: IwfH6vAH0rZWK3wL2aK3hTopsWVb6t
#  bucketName: hzed-ccard #存储空间目录



# 第三方
thirdParty:
  pay:
    domain:                   http://10.10.30.112:8082 # 请求架构组bulepay域名地址
    loanTransactionUrl:       /bluepay/transferBalance  # 放款接口链接
    receiverTransactionUrl:   /bluepay/gatherDr # 收款接口链接
    getPaymentCodeUrl:        /bluepay/getPaymentCode #获取还款码接口
    checkAccountUrl:          /bluepay/checkAccount # 校验用户银行卡信息真实性
  risk:
    domain:                   http://10.10.30.141:49611 # 请求风控域名地址
    checkRiskEnableBorrowUrl: /api/risk/checkRiskEnableBorrow # 请求风控查询用户贷款资格
    idCardRecognitionUrl:     /api/risk/core/ocr   # 身份证识别
    faceRecognitionUrl:       /api/risk/core/faceComparison # 人脸识别
    contactsUrl:              /api/risk/Contacts/add    # 通讯录授权
    messagesUrl:              /api/risk/Sms/add    # 短信授权
    operatorSendSmsCodeUrl:   /api/riskOperator/createTaskAndlogin  # 运营商-发送验证码
    operatorAuthUrl:          /api/riskOperator/sendSmsCode  # 运营商-输入验证码认证
    identityInfoUrl:          /api/risk/core/identity   # 身份信息认证
    pushBidUrl:               /api/risk/auto/antifraud  # 风控审核
    facebookAndInsUrl:        /api/riskSocial/certificationNotify  # facebook和ins认证时数据推风控
    authPersonInfoUrl:        /api/risk/emercontact/push  # 个人信息认证时数据异步推风控
#======================================= 系统参数 开始 =======================================#
system:
  imgUploadPath: c:/imgUpload # 上传图片文件目录
  tokenExpire: 7 # token失效时间 7 天
  expected_audit_time_interval: 1440 # 预计审核时间间隔 单位分
  expected_lending_time_interval: 60 # 预计放款时间间隔 单位分
  expiredDay: 30 # 公告未读有效时间 单位天
  authFee: 50000 # 信息认证费
  reviewFee: 50000 # 信息审核费
  handlingFee: 20000 # 手续费
  # 地区 id-ID：印尼
  local: id-ID
  # 短信催账提前天数
  daysInAdvance: 3
  # 请求前端H5页面链接
  H5MessageUrl: http://10.10.20.163:8801/article/MessagePushDetail.html?id=

  # 允许注册的三大运营商手机号前缀
  MobilePrefix:
    Telkomsel: 0811,0812,0813,0821,0822,0823,0852
    XL: 0817,0818,0819,0859,0877,0878
    Indosat: 0814,0815,0816,0855,0856,0858


  # 定时任务 启动标志 周期
  job:
    # 风控审核
    pushBid: false
    pushBidCron: 0/5 * * * * ?
    # 放款
    bankLoan: false
    bankLoanCron: 0 */2 * * * ?
    # 处理还款信息流
    repayInfoFlow: false
    repayInfoFlowCron: 0/5 * * * * ?
    # 神策进件
    saInData: false
    saInDataCron:  0/5 * * * * ?
    # 神策借款成功
    saLoanSuccess: false
    saLoanSuccessCron:  0 */1 * * * ?
    # 神策还款
    saRepaymentSuccess: false
    saRepaymentSuccessCron: 0 */1 * * * ?
    # 短信催账
    checkBill: false
    checkBillCron: 0 0 15 * * ?

#======================================= 系统参数 结束 =======================================#