
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.31.242.13:4657/indonesia_p2p?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
    username: ENC(5WL81/3csDd+UcP6zGWQcS/H9Kmt4jIM) # 用户密文
    password: ENC(wINTBNYGGATXFrG6CyuCKl5WhOZbxGuhnyzzX0DKAu7urxrqSZgk3A==) # 密码密文
  # Resid相关配置
  redis:
    database: 0
    host: 172.31.242.13
    port: 4467
    password: sieKDFOA32fd9E3FDd
  # 国际化配置
  messages.cacheSeconds: 86400 # 缓存24小时
  # rabbitmq配置
  rabbitmq:
    host: 172.31.242.14
    port: 5672
    username: hzed_mq
    password: Hzed#_2018
    virtual-host: /

# 日志文件配置
logging:
  envNameCN: 生产环境 # 环境中文名
  emailTo: guichang@hzed.com,wuchengwu@hzed.com,huangfengjing@hzed.com # 邮件接收者，多个用逗号隔开

# 第三方
thirdParty:
  pay.domain:   http://172.31.242.15:8181 # 请求架构组bulepay域名地址
  risk.domain:  http://172.31.242.17:9611 # 请求风控域名地址
#======================================= 系统参数 开始 =======================================#
system:
  imgUploadPath: /data/imgUpload # 上传图片文件目录
  tokenExpire: 7 # token失效时间 7 天
  expected_audit_time_interval: 1440 # 预计审核时间间隔 单位分
  expected_lending_time_interval: 60 # 预计放款时间间隔 单位分
  # 地区 id-ID：印尼
  local: id-ID
  # 短信催账提前天数
  daysInAdvance: 3

  # 定时任务 启动标志 周期
  job:
    # 风控审核
    pushBid: true
    pushBidCron: 0 */5 * * * ?
    # 放款
    bankLoan: true
    bankLoanCron: 0 */5 * * * ?
    # 处理还款信息流
    repayInfoFlow: true
    repayInfoFlowCron: 0 */2 * * * ?
    # 神策进件
    saInData: true
    saInDataCron: 0 */2 * * * ?
    # 神策借款成功
    saLoanSuccess: true
    saLoanSuccessCron: 0 */2 * * * ?
    # 神策还款
    saRepaymentSuccess: true
    saRepaymentSuccessCron: 0 */2 * * * ?
    # 提还短信D0 每天5条，4点、10点、12点半、4点、8点
    checkBillD0: true
    checkBillCronD0: 0 0 4,10,12,16,20 * * ?
    # 提还短信D1 每天2条，早上7点半，中午12点半
    checkBillD1: true
    checkBillCronD1: 0 30 7,12 * * ?
    # 提还短信D2 每天1条，12点半发
    checkBillD2: true
    checkBillCronD2: 0 30 12 * * ?
#======================================= 系统参数 结束 =======================================#


