spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.30.36:3306/easy_get_test?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
    username: ENC(wD8fKKuFx4GcCaFsCnj3eg==) # 用户密文 明文用户：root
    password: ENC(c2BWF7K9ElGY0GZbWDmpfAaUhTuqYvie) # 密码密文 明文密码：rootroot
  # rabbitmq配置
  rabbitmq:
    host: 10.10.30.112
    port: 32999
    username: user
    password: password
    virtual-host: /
# 日志文件配置
logging:
  logHome: /work/easy-get-8150/logs # 日志路径
  envNameCN: 测试环境 # 环境中文名
  emailTo: guichang@hzed.com,wuchengwu@hzed.com,huangfengjing@hzed.com # 邮件接收者，多个用逗号隔开

# 第三方
thirdParty:
  pay.domain: http://10.10.30.114:8081 # 请求bulepay域名地址
  risk.domain: http://10.10.30.141:49611 # 请求风控域名地址

#======================================= 系统参数 开始 =======================================#
system:
  imgUploadPath: /work/easy-get-8150/imgUpload # 上传图片文件目录

  # 定时任务 启动标志 周期
  job:
    # 风控审核
    pushBid: true
    pushBidCron: 0/5 * * * * ?
    # 放款
    bankLoan: true
    bankLoanCron: 0 */2 * * * ?
    # 处理还款信息流
    repayInfoFlow: true
    repayInfoFlowCron: 0/5 * * * * ?
    # 神策进件
    saInData: true
    saInDataCron: 0 */1 * * * ?
    # 神策借款成功
    saLoanSuccess: true
    saLoanSuccessCron: 0 */1 * * * ?
    # 神策还款
    saRepaymentSuccess: true
    saRepaymentSuccessCron: 0 */1 * * * ?
    # 催账短信
    checkBill: true
    checkBillCron: 0 0 15 * * ?
#======================================= 系统参数 结束 =======================================#


