spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://10.10.30.36:3306/easy_get_test?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
    url: jdbc:mysql://10.10.30.36:3306/easy_get_pre?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
    username: ENC(wD8fKKuFx4GcCaFsCnj3eg==) # 用户密文 明文用户：root
    password: ENC(c2BWF7K9ElGY0GZbWDmpfAaUhTuqYvie) # 密码密文 明文密码：rootroot
  # rabbitmq配置
  rabbitmq:
    host: 10.10.30.139
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
# 日志文件配置
logging:
  logHome: /work/easy-get-8150/logs # 日志路径
  envNameCN: 测试环境 # 环境中文名
  emailTo: guichang@hzed.com,wuchengwu@hzed.com,huangfengjing@hzed.com # 邮件接收者，多个用逗号隔开

# 第三方
thirdParty:
  pay.domain: http://10.10.30.112:8081 # 请求bulepay域名地址
  risk.domain: http://10.10.30.141:49611 # 请求风控域名地址

#======================================= 系统参数 开始 =======================================#
system:
  imgUploadPath: /home/hzed-dev/easy-get/imgUpload # 上传图片文件目录

  # 定时任务 启动标志 周期
  job:
    # 风控审核
    pushBid: true
    pushBidCron: 0 */1 * * * ?
    # 放款
    bankLoan: true
    bankLoanCron: 0 */2 * * * ?
    # 处理还款信息流
    repayInfoFlow: true
    repayInfoFlowCron: 0/5 * * * * ?
    # 神策进件
    saInData: true
    saInDataCron: 0 */1 * * * ?
    # 神策借款成功
    saLoanSuccess: true
    saLoanSuccessCron: 0 */1 * * * ?
    # 神策还款
    saRepaymentSuccess: true
    saRepaymentSuccessCron: 0 */1 * * * ?
    # 提还短信D0 每天5条，4点、10点、12点半、4点、8点
    checkBillD0: true
    checkBillCronD0: 0 0 4,10,12,16,20 * * ?
    # 提还短信D1 每天2条，早上7点半，中午12点半
    checkBillD1: true
    checkBillCronD1: 0 30 7,12 * * ?
    # 提还短信D2 每天1条，12点半发
    checkBillD2: true
    checkBillCronD2: 0 30 12 * * ?
#======================================= 系统参数 结束 =======================================#


