# 应用端口号
server.port: 8150
# 默认根路径
server.context-path: /hzed/easy-get

# TODO 密码加密 https://blog.csdn.net/linhongwangok/article/details/79076178;https://github.com/ulisesbocchio/jasypt-spring-boot
spring:
  resources.static-locations: file:${system.imgUploadPath} # 静态资源文件路径，多个用逗号隔开 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  profiles.active: dev # 环境
  application.name: easy-get
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.30.91:3306/easy-get?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
    username: root
    password: 123456
  # Resid相关配置
  redis:
    database: 0
    host: 10.10.30.37
    port: 3037
    password: masterpass
  messages:
    basename: i18n/messages
    encoding: utf-8
    cacheSeconds: 86400 # 24小时
# 日志文件配置
logging:
  config: classpath:config/logback-spring.xml # 配置文件路径
  logHome: D:/logs/easy-get # 日志路径
  appNameCN: 印尼借贷项目 # 应用中文名
  envNameCN: 开发环境 # 环境中文名
  emailTo: guichang@hzed.com # 邮件接收者，多个用逗号隔开

# 阿里云配置
aliyun:
  endpoint: http://oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAIxzelwCX3fyTQ
  accessKeySecret: IwfH6vAH0rZWK3wL2aK3hTopsWVb6t
  bucketName: hzed-ccard #存储空间目录

# 第三方
thirdParty:
  pay:
    domain: http://10.10.30.114:8081 # 请求架构组bulepay域名地址
    loanTransactionUrl: /bluepay/transferBalance  # 放款接口链接
    receiverTransactionUrl: /bluepay/gatherDr # 收款接口链接
    getPaymentCodeUrl: /bluepay/getPaymentCode #获取还款码接口
  risk:
    domain: http://10.10.20.202:9611 # 请求风控域名地址
    checkRiskEnableBorrowUrl: /api/risk/checkRiskEnableBorrow #请求风控查询用户贷款资格
    idCardRecognitionUrl: /api/risk/core/ocr #身份证识别
    faceRecognitionUrl: /api/risk/core/faceComparison #人脸识别
    contactsUrl: /api/risk/Contacts/add #通讯录授权
    messagesUrl: /api/risk/Sms/add #短信授权
    operatorSendSmsCodeUrl: /api/riskOperator/createTaskAndlogin  #运营商-发送验证码
    operatorAuthUrl: /app/riskOperator/sendSmsCode  #运营商-输入验证码认证

#======================================= 系统参数 开始 =======================================#
system:
  imgUploadPath: c:/imgUpload # 上传图片文件目录
  tokenExpire: 7 # token失效时间 7 天
  expected_audit_time_interval: 1440 #预计审核时间间隔 单位分
  expected_lending_time_interval: 60 #预计放款时间间隔 单位分
  #定时任务
  job:
    pushBid: false # 推送资产
    pushBidCron: 0/5 * * * * ?
    bankLoan: false # 放款
    bankLoanCron: 0/5 * * * * ?
    repayInfoFlow: false # 还款信息流
    repayInfoFlowCron: 0/5 * * * * ?


#======================================= 系统参数 结束 =======================================#