### 风控审核回调
POST http://localhost:8150/hzed/easy-get/callback/riskCallback/pushBidCallback
Content-Type: application/json
imei:123123
i18n:zh-CN
appKey:easyGet
platform:android
version:1.0.0
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoie1wibW9iaWxlXCI6XCIwODEyMTU1MTExMVwiLFwidXNlcklkXCI6MTI2MTc3NjcwMTczNDMzODU2fSIsImV4cCI6MTUzNDQwMjA0OX0.GEr_GlTz5khb9IiXSXFos7cq_5KQQd7aPdvu8aZpmpc

{
    "handleTime": "1533282302188",
    "resultCode": "8",
    "message": "",
    "bidId": "1",
    "loanAmount": "600000.0",
    "manual":1,
    "updateBy":"123123"
}

###