### 申请借款
POST http://localhost:8150/hzed/easy-get/api/loan/submitLoan
Accept: application/json;charset=UTF-8
Cache-Control: no-cache
Content-Type: application/json
imei: 123123
i18n: en-US
appKey: 1233
platform: android
version: 1.1.0
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoie1wibW9iaWxlXCI6XCIxNDQ1MTI1MzYzNVwiLFwidXNlcklkXCI6MTA3NjU5NDQxNzA4ODY3NTg0fSIsImV4cCI6MTUzMDA2OTI5OH0.sXxiBgAhobKTiVzEIcgE1_K3ZgzR6vuTvjsqq3Xjms0

{
  "applyAmount":"2000",
  "period":"14",
  "inBank":"122",
  "inAccount":"15910086222",
  "purposeId":"1"
}