### 发送验证码
POST http://localhost:8150/hzed/easy-get/api/login/sendSmsCode
#POST http://10.10.30.92:8150/hzed/easy-get/api/login/sendSmsCode
Accept: application/json;charset=UTF-8;
Content-Type: application/json
imei:1
i18n:zh-CN
appKey:easyGet
platform:android
version:1.0.0

{
    "mobile":"0181721551111"
}

### 用户登录
POST http://localhost:8150/hzed/easy-get/api/login/loginByCode
#POST http://m.rupiahget.id/hzed/easy-get/api/login/loginByCode
#POST http://10.10.30.133:8160/hzed/easy-get/api/login/loginByCode
#POST https://rupiahget.id/hzed/easy-get/api/login/loginByCode
#POST http://149.129.212.112:8160/hzed/easy-get/api/login/loginByCode
Accept: application/json;charset=UTF-8
Cache-Control: no-cache
Content-Type: application/json
imei: 666666
i18n: en-US
appKey: 1233
platform: android
version: 1.1.0

{
	"device":"123",
	"mobile":"013900139600",
	"smsCode":"0000",
	"anonymousId":"123"
}

###