### 测试还款接口
POST http://10.10.30.133:8160/hzed/easy-get/api/test/testRepayment
#POST http://localhost:8150/hzed/easy-get/api/test/manMadeMqCallback
Accept: application/json;charset=UTF-8;
Content-Type: application/json

{
    "transactionId":"128716291312984064hzed",
    "payType":"atm",
    "bankType":"permata",
    "paymentCode":"8359180815498245",
    "msisdn":"08771111102",
    "price":"100000.00",
    "cardNo":"21934189228383587872"
}

### 人工处理MQ回调
#POST http://10.10.30.92:8150/hzed/easy-get/api/test/manMadeMqCallback
POST https://rupiahget.id/hzed/easy-get/api/test/manMadeMqCallback
#POST http://localhost:8150/hzed/easy-get/api/test/manMadeMqCallback
Accept: application/json;charset=UTF-8;
Content-Type: application/json

{
    "bt_id": "1673022141533729002097OYzEUl",
    "cmd": "CFM",
    "currency": "IDR",
    "encrypt": "4b647ebd6c2de5f4da71ce4d77f4279e",
    "interfacetype": "cashout",
    "msisdn": "6281380094372",
    "operator": "BCA",
    "paytype": "pre",
    "price": 480000,
    "productid": 1673,
    "status": "200",
    "t_id": "126239442070712320hzed"
}

###