### 测试还款接口
POST http://10.10.30.92:8150/hzed/easy-get/api/test/testRepayment
#POST http://localhost:8150/hzed/easy-get/api/test/manMadeMqCallback
Accept: application/json;charset=UTF-8;
Content-Type: application/json

{
    "transactionId": "116061068727820288hzed",
    "payType": "atm",
    "bankType": "permata",
    "paymentCode": "8359180711750264",
    "msisdn": "8615926633889",
    "price": "506000.00",
    "cardNo": "21934189228383587872"
}

### 人工处理MQ回调
POST http://10.10.30.92:8150/hzed/easy-get/api/test/manMadeMqCallback
#POST http://localhost:8150/hzed/easy-get/api/test/manMadeMqCallback
Accept: application/json;charset=UTF-8;
Content-Type: application/json

{
    "bt_id": "1605042141530530417608YMWasB",
    "cmd": "CFM",
    "currency": "IDR",
    "encrypt": "9b223fb0ae1f40d6d93be7016ca945a5",
    "interfacetype": "cashout",
    "msisdn": "8613900139021",
    "operator": "PERMATA",
    "paytype": "pre",
    "price": 480000,
    "productid": 1605,
    "status": "200",
    "t_id": "112823616491888640hzed"
}