###交易记录
POST http://localhost:8150/hzed/easy-get/api/user/getTransactionRecord
Content-Type: application/json
imei: 666666
i18n: zh-CN
appKey: easyGet
platform: android
version: 1.0.0
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoie1wibW9iaWxlXCI6XCIwMTM5MDAxMzk2MDBcIixcInVzZXJJZFwiOjExNTY2MDc1MjYxMDAwOTA4OH0iLCJleHAiOjE1MzU1OTgxMjZ9.ERYHuQjZgxBRs16Nmpt1xGnhrSie2WbJR3VMCLzAiaQ

{
    "pageNo":0,
    "pageSize":10
}

###