###交易记录
POST http://localhost:8150/hzed/easy-get/api/user/getTransactionRecord
Content-Type: application/json
imei:1
i18n:zh-CN
appKey:easyGet
platform:android
version:1.0.0
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoie1wibW9iaWxlXCI6XCIxNTkxMDA4NjU1NVwiLFwidXNlcklkXCI6MTA1NTM0MzE1NjY4MzE2MTYwfSIsImV4cCI6MTUzMDE1MTUwMn0.POUZ5GrN_CK2rlnO77doW6AAEAYRgpDMX8RII8wd6xs

{
    "pageNo":0,
    "pageSize":5
}